# Generated by Django 6.0.5 on 2026-05-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="O'lcham"),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="O'lcham"),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.JSONField(blank=True, default=dict, verbose_name="O'lchamlar"),
        ),
        migrations.AddField(
            model_name='sessioncartitem',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="O'lcham"),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'size')},
        ),
    ]
