# Generated by Django 6.0.5 on 2026-05-23 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cartitem_size_orderitem_size_product_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Rang')),
                ('size', models.CharField(max_length=20, verbose_name="O'lcham")),
                ('stock', models.IntegerField(default=0, verbose_name='Soni')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='SKU')),
                ('price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Qo'shimcha narx")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product')),
            ],
            options={
                'verbose_name': 'Mahsulot varianti',
                'verbose_name_plural': 'Mahsulot variantlari',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
    ]
