# Generated by Django 6.0.5 on 2026-05-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='can_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
