# Generated by Django 6.0.5 on 2026-05-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_order_options_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='Admin javobi'),
        ),
        migrations.AddField(
            model_name='review',
            name='admin_reply_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Javob vaqti'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='Javob berilgan'),
        ),
    ]
